from __future__ import annotations

from dataclasses import dataclass, field
import re
from urllib.parse import urlparse

from .bib_build import build_bibtex_preserving_fields
from .model import BibCandidate, BibInputEntry
from .normalizer import normalize_doi, normalize_year, norm_text
from .provenance import source_authority

# Fields a scholarly source is allowed to add or correct automatically.
# Unknown publisher-specific fields are retained when they already exist in the
# user's entry, but are not imported from remote metadata by default.
CANONICAL_REMOTE_FIELDS = {
    "author",
    "editor",
    "title",
    "booktitle",
    "journal",
    "series",
    "volume",
    "number",
    "edition",
    "pages",
    "articleno",
    "year",
    "month",
    "publisher",
    "address",
    "institution",
    "school",
    "isbn",
    "issn",
    "doi",
    "eprint",
    "archiveprefix",
    "primaryclass",
    "url",
    # Rich publisher metadata. These fields may only be imported from a
    # publisher/repository native export or publisher page metadata.
    "abstract",
    "keywords",
    "numpages",
    "location",
    "issue_date",
}

RICH_REMOTE_FIELDS = {
    "abstract",
    "keywords",
    "numpages",
    "location",
    "issue_date",
}

RICH_WRITE_SOURCE_KINDS = {
    "publisher_native_export",
    "repository_native_export",
    "publisher_page_metadata",
}

# Local annotations are preserved but never imported from remote records.
PRESERVE_ONLY_FIELDS = {
    "note",
    "annote",
    "howpublished",
    "urldate",
    "accessed",
    "copyright",
}

# Long textual fields are safe to add from a native publisher source, but an
# existing user value is not overwritten automatically. Publisher abstracts and
# keyword lists can differ by formatting or editorial revision.
RICH_ADD_ONLY_FIELDS = {"abstract", "keywords"}

GENERIC_ENTRY_TYPES = {"misc", "unpublished", "techreport"}
PUBLISHED_ENTRY_TYPES = {"article", "inproceedings", "incollection", "inbook", "book", "proceedings"}


@dataclass
class MergeResult:
    entry_type: str
    fields: dict[str, str]
    field_order: list[str]
    bibtex: str
    added: list[str] = field(default_factory=list)
    updated: list[str] = field(default_factory=list)
    preserved: list[str] = field(default_factory=list)
    skipped_remote: list[str] = field(default_factory=list)
    field_sources: dict[str, str] = field(default_factory=dict)
    supplemental_sources: list[str] = field(default_factory=list)
    entry_type_changed: bool = False
    removed_empty: list[str] = field(default_factory=list)

    @property
    def changed(self) -> bool:
        return bool(self.added or self.updated or self.removed_empty or self.entry_type_changed)

    def to_jsonable(self) -> dict[str, object]:
        return {
            "entry_type": self.entry_type,
            "entry_type_changed": self.entry_type_changed,
            "fields_added": self.added,
            "fields_updated": self.updated,
            "empty_fields_removed": self.removed_empty,
            "original_fields_preserved": self.preserved,
            "remote_fields_skipped": self.skipped_remote,
            "field_sources": self.field_sources,
            "supplemental_sources": self.supplemental_sources,
            "bibtex": self.bibtex,
        }


def merge_candidate_into_entry(
    original: BibInputEntry,
    candidate: BibCandidate,
    *,
    allow_entry_type_upgrade: bool = True,
    supplemental_candidates: list[BibCandidate] | None = None,
) -> MergeResult:
    """Merge trusted remote metadata without deleting user fields.

    The remote record is an update source, not a replacement template. Every
    original field remains unless the remote source supplies a non-empty value
    for the same canonical field and the values are materially different.
    """

    removed_empty = sorted(
        key for key, value in original.fields.items() if not str(value or "").strip()
    )
    merged = {
        key: value
        for key, value in original.fields.items()
        if str(value or "").strip()
    }
    order = [key for key in original.field_order if key in merged]

    # Registry content-negotiation BibTeX is generated by a generic schema
    # transform. Treat it as identity evidence only, never as a write source.
    # This guard makes the policy safe even if callers bypass resolve.py.
    if candidate.source_kind == "registry_transform":
        bibtex = build_bibtex_preserving_fields(
            entry_type=original.entry_type,
            key=original.key,
            fields=merged,
            field_order=order,
        )
        return MergeResult(
            entry_type=original.entry_type,
            fields=merged,
            field_order=order,
            bibtex=bibtex,
            preserved=sorted(original.fields),
            skipped_remote=["registry_transform:evidence_only"],
            removed_empty=removed_empty,
        )
    added: list[str] = []
    updated: list[str] = []
    preserved: list[str] = []
    skipped: list[str] = []
    field_sources: dict[str, str] = {}
    supplemental_sources: list[str] = []

    candidate_fields = {
        str(key).strip().lower(): _clean_remote_value(value)
        for key, value in candidate.fields.items()
    }
    _normalize_acm_article_number_fields(candidate_fields)

    # A DOI URL is useful when no URL exists, but normalize obsolete dx.doi.org
    # links and never replace a useful original page URL with a DOI redirect.
    remote_doi = normalize_doi(candidate_fields.get("doi", "")) if candidate_fields.get("doi") else ""

    for key, value in candidate_fields.items():
        if not value:
            continue
        if key not in CANONICAL_REMOTE_FIELDS or key in PRESERVE_ONLY_FIELDS:
            skipped.append(key)
            continue
        if _skip_synthetic_preprint_field(original, candidate, key, value):
            skipped.append(f"{key}:synthetic_preprint_representation")
            continue
        if key in RICH_REMOTE_FIELDS and candidate.source_kind not in RICH_WRITE_SOURCE_KINDS:
            skipped.append(f"{key}:source_not_authoritative")
            continue

        if key == "url":
            value = _normalize_remote_url(value, remote_doi)
            if not value:
                skipped.append(key)
                continue
            if merged.get("url"):
                current_url = str(merged["url"]).strip()
                if (
                    _identifier_recovery_allowed(candidate)
                    and _url_is_doi_redirect(current_url)
                    and remote_doi
                    and normalize_doi(current_url) != remote_doi
                ):
                    merged[key] = value
                    updated.append(key)
                    field_sources[key] = candidate.source
                    continue
                # Existing URLs may point to a project page, publisher page, or
                # archived resource. Preserve them instead of replacing them
                # with a generic DOI redirect.
                preserved.append(key)
                continue

        if key == "doi":
            value = normalize_doi(value)
            if not value:
                continue

        if key not in merged or not str(merged[key]).strip():
            merged[key] = value
            if key not in order:
                order.append(key)
            added.append(key)
            field_sources[key] = candidate.source
            continue

        current = str(merged[key]).strip()
        if _field_values_equivalent(key, current, value):
            preserved.append(key)
            continue

        if key in RICH_ADD_ONLY_FIELDS:
            preserved.append(key)
            skipped.append(f"{key}:existing_rich_field_preserved")
            continue

        if _remote_value_is_less_informative(key, current, value, candidate):
            preserved.append(key)
            skipped.append(f"{key}:less_informative_remote")
            continue

        # Stable identifiers must never be erased. A conflicting identifier
        # should already have blocked automatic application in resolve.py; this
        # guard keeps the merge layer safe if called independently.
        if key == "doi" and normalize_doi(current) != normalize_doi(value):
            if not _identifier_recovery_allowed(candidate):
                preserved.append(key)
                skipped.append("conflicting_doi")
                continue
        if key == "isbn" and _normalize_isbn(current) != _normalize_isbn(value):
            preserved.append(key)
            skipped.append("conflicting_isbn")
            continue

        merged[key] = value
        updated.append(key)
        field_sources[key] = candidate.source

    # Candidate omission is never deletion. Record all original-only fields as
    # preserved so the audit report makes that guarantee visible.
    for key in original.fields:
        if key not in candidate_fields and key not in preserved:
            preserved.append(key)

    for supplemental in sorted(
        supplemental_candidates or [],
        key=lambda item: (source_authority(item), item.source_priority, item.score),
        reverse=True,
    ):
        if supplemental is candidate or supplemental.confidence not in {"exact", "high"}:
            continue
        if supplemental.source_kind == "registry_transform":
            skipped.append("registry_transform:evidence_only")
            continue
        used = _add_missing_supplemental_fields(
            merged=merged,
            order=order,
            candidate=supplemental,
            added=added,
            skipped=skipped,
            field_sources=field_sources,
        )
        if used:
            supplemental_sources.append(supplemental.source)

    entry_type = original.entry_type
    entry_type_changed = False
    remote_type = _candidate_entry_type(candidate)
    if (
        allow_entry_type_upgrade
        and original.entry_type in GENERIC_ENTRY_TYPES
        and remote_type in PUBLISHED_ENTRY_TYPES
        and _formal_type_upgrade_allowed(candidate)
    ):
        entry_type = remote_type
        entry_type_changed = entry_type != original.entry_type

    bibtex = build_bibtex_preserving_fields(
        entry_type=entry_type,
        key=original.key,
        fields=merged,
        field_order=order,
    )
    return MergeResult(
        entry_type=entry_type,
        fields=merged,
        field_order=order,
        bibtex=bibtex,
        added=sorted(set(added)),
        updated=sorted(set(updated)),
        preserved=sorted(set(preserved)),
        skipped_remote=sorted(set(skipped)),
        field_sources=dict(sorted(field_sources.items())),
        supplemental_sources=list(dict.fromkeys(supplemental_sources)),
        entry_type_changed=entry_type_changed,
        removed_empty=removed_empty,
    )


def _remote_field_allowed(candidate: BibCandidate, key: str) -> bool:
    if key not in CANONICAL_REMOTE_FIELDS or key in PRESERVE_ONLY_FIELDS:
        return False
    if key in RICH_REMOTE_FIELDS and candidate.source_kind not in RICH_WRITE_SOURCE_KINDS:
        return False
    return True


def _identifier_recovery_allowed(candidate: BibCandidate) -> bool:
    return "identifier_recovery_verified" in candidate.evidence


def _formal_type_upgrade_allowed(candidate: BibCandidate) -> bool:
    if candidate.confidence == "exact":
        return not _candidate_represents_preprint(candidate)
    if candidate.confidence != "high":
        return False
    if candidate.source_kind not in {
        "publisher_native_export",
        "repository_native_export",
        "bibliographic_index_export",
    }:
        return False
    evidence = set(candidate.evidence)
    deterministic = bool(
        evidence.intersection(
            {
                "dblp_deterministic_bib_endpoint",
                "usenix_export_link",
                "acl_deterministic_bib_endpoint",
                "springer_deterministic_export",
                "publisher_native_export",
            }
        )
    )
    return deterministic and not _candidate_represents_preprint(candidate)


def _candidate_represents_preprint(candidate: BibCandidate) -> bool:
    family = (candidate.source_family or candidate.source).lower()
    doi = normalize_doi(candidate.fields.get("doi", ""))
    journal = norm_text(candidate.fields.get("journal", ""))
    url = (candidate.source_url or candidate.fields.get("url", "")).lower()
    return bool(
        family == "arxiv"
        or doi.startswith("10.48550/arxiv.")
        or journal == "corr"
        or "arxiv.org" in url
        or "/journals/corr/" in url
    )


def _url_is_doi_redirect(value: str) -> bool:
    host = urlparse(value.strip()).netloc.lower().removeprefix("www.")
    return host in {"doi.org", "dx.doi.org"}


def _skip_synthetic_preprint_field(
    original: BibInputEntry,
    candidate: BibCandidate,
    key: str,
    value: str,
) -> bool:
    """Keep arXiv citations compact instead of importing DBLP/registry wrappers.

    For an entry that is already explicitly an arXiv preprint, CoRR, the
    ``abs/...`` volume, the DataCite 10.48550 DOI, and ``publisher=arXiv`` are
    alternate renderings rather than useful repairs. The stable arXiv eprint
    and URL remain writable. A formal conference/journal candidate is not
    filtered by this rule.
    """

    archive = norm_text(original.fields.get("archiveprefix", ""))
    has_arxiv_eprint = bool(original.fields.get("eprint")) and archive == "arxiv"
    if not has_arxiv_eprint:
        return False
    family = (candidate.source_family or candidate.source).lower()
    candidate_doi = normalize_doi(candidate.fields.get("doi", ""))
    journal = norm_text(candidate.fields.get("journal", ""))
    volume = norm_text(candidate.fields.get("volume", ""))
    is_arxiv_rendering = bool(
        family == "arxiv"
        or candidate_doi.startswith("10.48550/arxiv.")
        or journal == "corr"
        or volume.startswith("abs ")
    )
    return is_arxiv_rendering and key in {"doi", "journal", "volume", "publisher"}


def _normalize_acm_article_number_fields(fields: dict[str, str]) -> None:
    """Keep ACM article identifiers out of the issue-number field.

    ACM native exports may expose values such as ``Article 110`` or
    ``Article FSE037`` through the generic ``number`` property while also
    exposing the real issue designation separately. In BibTeX these values
    belong in ``articleno``; replacing ``number = {FSE}`` or ``number = {3}``
    with an article identifier corrupts the journal citation.
    """

    value = str(fields.get("number", "") or "").strip()
    match = re.fullmatch(r"(?i)article\s+(.+)", value)
    if not match:
        return
    article = match.group(1).strip()
    if article and not fields.get("articleno"):
        fields["articleno"] = article
    fields.pop("number", None)


def _skip_synthetic_preprint_field_from_fields(
    merged: dict[str, str],
    candidate: BibCandidate,
    key: str,
) -> bool:
    """Apply the arXiv compact-citation rule to supplemental sources too."""

    archive = norm_text(merged.get("archiveprefix", ""))
    has_arxiv_eprint = bool(merged.get("eprint")) and archive == "arxiv"
    if not has_arxiv_eprint:
        return False
    family = (candidate.source_family or candidate.source).lower()
    candidate_doi = normalize_doi(candidate.fields.get("doi", ""))
    journal = norm_text(candidate.fields.get("journal", ""))
    volume = norm_text(candidate.fields.get("volume", ""))
    is_arxiv_rendering = bool(
        family == "arxiv"
        or candidate_doi.startswith("10.48550/arxiv.")
        or journal == "corr"
        or volume.startswith("abs ")
        or volume.startswith("abs/")
    )
    return is_arxiv_rendering and key in {"doi", "journal", "volume", "publisher"}


def _candidate_entry_type(candidate: BibCandidate) -> str:
    # Candidates do not currently store entry_type separately. Parse it from
    # their generated BibTeX when available.
    text = candidate.bibtex or ""
    match = re.match(r"\s*@([A-Za-z]+)", text)
    return match.group(1).lower() if match else ""


def _clean_remote_value(value: object) -> str:
    text = str(value or "").strip()
    if text.lower() in {"none", "null", "n/a", "na", "undefined", "-"}:
        return ""
    return text


def _normalize_remote_url(value: str, doi: str) -> str:
    value = value.strip()
    parsed = urlparse(value)
    if parsed.scheme not in {"http", "https"}:
        return ""
    host = parsed.netloc.lower()
    if host in {"dx.doi.org", "www.doi.org", "doi.org"}:
        resolved = normalize_doi(parsed.path.lstrip("/")) or doi
        return f"https://doi.org/{resolved}" if resolved else ""
    return value


def _field_values_equivalent(field: str, left: str, right: str) -> bool:
    if field == "doi":
        return normalize_doi(left) == normalize_doi(right)
    if field == "year":
        return normalize_year(left) == normalize_year(right)
    if field in {"author", "editor"}:
        return _author_identity_signature(left) == _author_identity_signature(right)
    if field == "pages":
        return _normalize_pages(left) == _normalize_pages(right)
    if field == "month":
        return _normalize_month(left) == _normalize_month(right)
    if field == "isbn":
        return _normalize_isbn(left) == _normalize_isbn(right)
    if field == "url":
        return _normalize_url_for_compare(left) == _normalize_url_for_compare(right)
    return norm_text(left) == norm_text(right)


def _author_identity_signature(value: str) -> tuple[tuple[str, str], ...]:
    """Compare author identity without treating name presentation as metadata.

    `Sicheng Luo`, `Luo, Sicheng`, and `Luo, S.` resolve to the same family name
    and first-given initial. This prevents registry renderers from replacing
    full names with initials or merely reversing display order.
    """

    result: list[tuple[str, str]] = []
    for raw_name in re.split(r"\s+and\s+", value, flags=re.I):
        cleaned = norm_text(raw_name)
        if not cleaned:
            continue
        if "," in raw_name:
            family_raw, given_raw = raw_name.split(",", 1)
            family_tokens = norm_text(family_raw).split()
            given_tokens = norm_text(given_raw).split()
        else:
            tokens = cleaned.split()
            family_tokens = tokens[-1:] if tokens else []
            given_tokens = tokens[:-1]
        family = " ".join(family_tokens)
        first_initial = given_tokens[0][0] if given_tokens and given_tokens[0] else ""
        result.append((family, first_initial))
    return tuple(result)


def _remote_value_is_less_informative(
    field: str,
    current: str,
    remote: str,
    candidate: BibCandidate,
) -> bool:
    # Structured registries and their BibTeX transforms frequently truncate
    # titles or reduce full given names to initials. They remain useful for
    # identity and factual checks, but must not degrade richer local metadata.
    if field in {"author", "editor"}:
        if _author_identity_signature(current) == _author_identity_signature(remote):
            return _information_length(current) > _information_length(remote)

    if candidate.source_kind in {"registry_metadata", "registry_transform", "bibliographic_index", "bibliographic_index_export"}:
        current_norm = norm_text(current)
        remote_norm = norm_text(remote)
        if field == "title" and current_norm and remote_norm:
            if current_norm.startswith(remote_norm) and len(current_norm) > len(remote_norm) + 8:
                return True
            current_tokens = set(current_norm.split())
            remote_tokens = set(remote_norm.split())
            if remote_tokens and remote_tokens < current_tokens and len(remote_tokens) <= 0.8 * len(current_tokens):
                return True
        if field in {"booktitle", "journal"} and current_norm and remote_norm:
            # Registry/index records often omit an acronym, edition label, or
            # year suffix from an otherwise identical venue. That is a
            # representation difference, not a factual correction.
            if remote_norm in current_norm and current_norm != remote_norm:
                return True
    return False


def _information_length(value: str) -> int:
    return len(re.sub(r"[^A-Za-z0-9]+", "", value))


def _add_missing_supplemental_fields(
    *,
    merged: dict[str, str],
    order: list[str],
    candidate: BibCandidate,
    added: list[str],
    skipped: list[str],
    field_sources: dict[str, str],
) -> bool:
    used = False
    fields = {
        str(key).strip().lower(): _clean_remote_value(value)
        for key, value in candidate.fields.items()
    }
    remote_doi = normalize_doi(fields.get("doi", "")) if fields.get("doi") else ""
    _normalize_acm_article_number_fields(fields)
    for key, value in fields.items():
        if not value or not _remote_field_allowed(candidate, key):
            continue
        if _skip_synthetic_preprint_field_from_fields(merged, candidate, key):
            skipped.append(f"{key}:synthetic_preprint_representation")
            continue
        if key in merged and str(merged[key]).strip():
            continue
        if key == "doi":
            value = normalize_doi(value)
        elif key == "url":
            value = _normalize_remote_url(value, remote_doi)
        if not value:
            continue
        merged[key] = value
        if key not in order:
            order.append(key)
        added.append(key)
        field_sources[key] = candidate.source
        used = True
    return used


def _normalize_pages(value: str) -> str:
    return re.sub(r"[\s\-–—]+", "-", value.strip()).strip("-")


def _normalize_month(value: str) -> str:
    mapping = {
        "jan": "january", "feb": "february", "mar": "march", "apr": "april",
        "may": "may", "jun": "june", "jul": "july", "aug": "august",
        "sep": "september", "sept": "september", "oct": "october",
        "nov": "november", "dec": "december",
    }
    token = norm_text(value)
    return mapping.get(token, token)


def _normalize_isbn(value: str) -> str:
    return re.sub(r"[^0-9xX]", "", value).lower()


def _normalize_url_for_compare(value: str) -> str:
    parsed = urlparse(value.strip())
    host = parsed.netloc.lower().removeprefix("www.")
    path = parsed.path.rstrip("/")
    return f"{host}{path}?{parsed.query}".rstrip("?")
